name: Rails
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  run-local-rails-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Check prerequisites
        run: |
          python -V
          pip -V
          pip install -r ./.github/workflows/requirements.txt
          python ./.github/workflows/try_issues.py
      - name: Set up Ruby 2.7.4
        uses: ruby/setup-ruby@v1 # https://github.com/ruby/setup-ruby
        with:
          ruby-version: 2.7.4 # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically, any step doing bundle install (for the root Gemfile) or gem install bundler can be removed with bundler-cache: true
      - name: Run local RSpec tests
        run: |
          RAILS_ENV=test bundle exec rails db:migrate
          bundle exec rspec spec/
      - name: Run exercise automation
        run: |
          ./.github/workflows/exercise_automation
